---
- name: Configure Services
  hosts: labproject
  become: true
  become_method: sudo

  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: /home/maks/.ssh/project-ssh-key

  tasks:

    # make sure nginx is installed
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
    
    # make sure that nginx is unmasked
    - name: Unmask nginx
      ansible.builtin.systemd:
        name: nginx
        masked: false

    # restart nginx
    - name: Restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted

    # disable the default site
    - name: Remove default nginx configuration
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    # copy over configuration for the new site
    - name: Add nginx configuration
      ansible.builtin.copy:
        src: "/home/maks/Documents/repos/mdudek2/ITMO-453-Monitoring-Metrics-Project/configs/hello-site.conf"
        dest: /etc/nginx/sites-available/hello-site.conf
        owner: root
        group: root
        mode: '0644'

    # copy the new website to each webserver
    - name: Copy website to servers
      ansible.builtin.copy:
        src: "/home/maks/Documents/repos/mdudek2/ITMO-453-Monitoring-Metrics-Project/html/index.html"
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

    # enable the site on nginx
    - name: Enable the site on nginx
      ansible.builtin.file:
        src: /etc/nginx/sites-available/hello-site.conf
        dest: /etc/nginx/sites-enabled/hello-site.conf
        state: link
        force: true

    # install node-exporter and nginx-exporter
    - name: Install exporters for metrics packages
      ansible.builtin.apt:
        name:
          - prometheus-node-exporter
          - prometheus-nginx-exporter
        state: present

    # copy the nginx metrics configuration file
    - name: Copy metrics.conf to nginx configuration
      ansible.builtin.copy:
        src: "/home/maks/Documents/repos/mdudek2/ITMO-453-Monitoring-Metrics-Project/configs/metrics.conf"
        dest: /etc/nginx/conf.d/metrics.conf
        owner: root
        group: root
        mode: '0644'

    # enable exporters
    - name: Enable metrics reporting services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
      loop:
        - prometheus-node-exporter
        - prometheus-nginx-exporter

    # start exporters
    - name: Start metrics reporting services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - prometheus-node-exporter
        - prometheus-nginx-exporter

    # validate nginx configuration
    - name: Test nginx configuration
      ansible.builtin.command:
        cmd: nginx -t
      changed_when: false

    # restart nginx to apply the new configuration
    - name: Restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted

- name: Configure prometheus to monitor the deployed website
  hosts: labproject
  become: true
  become_method: sudo

  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: /home/maks/.ssh/project-ssh-key

  tasks:
    
    # copy the config file
    - name: Copy the prometheus configuration file
      ansible.builtin.copy:
        src: "/home/maks/Documents/repos/mdudek2/ITMO-453-Monitoring-Metrics-Project/configs/prometheus.yml"
        dest: /etc/prometheus/prometheus.yml
        owner: root
        group: root
        mode: '0644'
    
    # restart prometheus to apply the configuration
    - name: Restart prometheus
      ansible.builtin.systemd:
        name: prometheus
        state: restarted

# install grafana on the prometheus node
- name: Install and configure Grafana
  hosts: labproject
  become: true
  become_method: sudo

  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: /home/maks/.ssh/project-ssh-key

  tasks:
    - name: Install required packages for Grafana
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - wget
          - gnupg
        state: present
        update_cache: true
    
    # add the repo and add the keys
    - name: Create APT keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Grafana GPG key
      ansible.builtin.get_url:
        url: https://apt.grafana.com/gpg-full.key
        dest: /etc/apt/keyrings/grafana.asc
        mode: "0644"

    - name: Add Grafana APT repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main"
        filename: grafana
        state: present
    
    # install grafana and enable the service
    - name: Install Grafana
      ansible.builtin.apt:
        name: grafana
        state: present
        update_cache: true

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and Start Grafana Service
      ansible.builtin.systemd:
        name: grafana-server
        enabled: true
        state: started
    
    # copy prometheus config and restart the service to apply the new source
    - name: Copy Prometheus Grafana Datasource
      ansible.builtin.copy:
        src: "/home/maks/Documents/repos/mdudek2/ITMO-453-Monitoring-Metrics-Project/configs/prometheus-grafana.yaml"
        dest: /etc/grafana/provisioning/datasources/prometheus-grafana.yaml
        owner: root
        group: root
        mode: "0644"

    - name: Restart Grafana to Enable DataSource
      ansible.builtin.systemd:
        name: grafana-server
        state: restarted
      